### PR TITLE
[Fixes #6] Eliminate unnescessary OS commands calling

### LINKED ISSUE #6: Handling output from external commands is synchronous
## Symptoms

Then something is heavily processing as external command, there's no output produced until it's successfully finished, what's confusing & counterproductive. Some output is being ignored in areas of code not being handled correctly.

## Technical details

Pattern like this is repeated all over:
```go
out, err = exec.Command("cp", "-rf", archivePath, dst).CombinedOutput()
if err != nil {
    ui.Error(fmt.Sprintf("error while copying file %v: %s", err, out))
    return multistep.ActionHalt
}
```

## Suggestion

Following [this pattern](https://stackoverflow.com/questions/25190971/golang-copy-exec-output-to-log/25191479#25191479) with type instance bound to common/global `Ui` instance passed from SDK seem to be way to go.

In general the idea is to write a type taking reference to `Ui` in constructor and then a method wrapping asynchronous execution which would attach to `cmd.Stdout` and `cmd.Stderr` instances forwarding to `ui.Message()` & `ui.Error()` respectively.

### PR DESCRIPTION
**Pull request by michalfita**
## Purpose

Unnecessary execution of operating systems commands is usually considered a bad practice (however, seem to be common practice in Go as it lacks many basic functions). It carries security risk we probably don't care that much as we'd never fully avoid calling OS commands, but we should avoid where we can.

## Scope
* Files calling `cp` and `mv` commands
* Scope creep: I found `test.yml` need renames inside, so I added (_I'm nasty I know, but in rush as well as I don't have a lot of time before New Year of hard work kicks in..._)

### CODE REVIEW

**Comment by dbast** [comment]
There are some code conflicts to solve... besides those: While I get the idea and reasoning to replace commands with go code, the entire packer-plugin-arm execution so far can be replaced with a bash script that executes a series of commands: dd + fdisk + mkfs + mount + tar -xf + qemu chroot etc... this is elegant by its own as the entire process can be easily debugged by getting all the commands + args from the packer log and then manually repeatedly running them manually step by step on cli to handle some low level issues and find some fixes... (this is an entire different idea than having static linked binaries with as less as possible dependencies to external commands)...  this possibility gets lost when more and more logic is converted to go code, so finding the shell equivalent command when reproducing stuff manually is then a harder thing. Also many of the shell commands used (e.g. *fdisk) didn't change much for years and are battle tested since decades to also handle all kind of special cases like sector paddings / offsets / alignments (in case of *fdisk).  

This is of course only valid if somebody prefers manipulating shell commands instead of go code during extensive debugging.

No matter where this is going, we should be at least aware about the potential consequences described above.

**Comment by dbast** [comment]
@michalfita what about doing a merge to master + release as base line before working on the "Reduce OS dependencies" milestone (as those changes will have consequences, see above)? ... all the required changes (switch to plugin + renames + docker-ghcr-switch + binary releases) should be on development already.

**Comment by michalfita** [comment]
> packer-plugin-arm execution so far can be replaced with a bash script that executes a series of commands

Why I understand this principle, it's not what I aim at in terms of fast efficient software. The **only** benefit of having this a Packer's plugin is the provisioner, everything else is replaceable... been there done that in BASH. And TBH I don't like Go so much I think about writing declarative tool in Rust (but probably would never have time to do it).

Now, I invested in this because I need this for my work and I want this to be as efficient as possible. The next fix I need (regarding debuggability) is commands output processing improvement (#6) as now in most cases only part of the output is spilled out depending whether the command was successful or failed.

**Comment by michalfita** [comment]
> what about doing a merge to master + release as base line before working on

Makes sense, let's not merge this for the moment. I'll just extract changes to `test.yml` separately, as this fixes that part of CI.

**Comment by dbast** [comment]
@michalfita I think this PR is good to go. I am fine with replacing simple commands like cp/mv/rm with the go equivalent for more speed / better in code error-handling etc.... we only have to be careful with replacing fdisk/sfdisk and the likes.

**Comment by michalfita** [comment]
> we only have to be careful with replacing fdisk/sfdisk and the likes

Priority on the list belongs to the command executor that streams output out in real time, not after the command ends. I have some ideas how to implement this, but as I'm not that familiar with Go it's going to be trial and error.

Benefits would be not only in better output to diagnose any problems as they appear, but the code is going to be simpler, easier to maintain and more consistent - at the moment the standard output or standard error are sometimes dropped, what can be misleading to any user willing to understand what's going on.

**Review by dbast — APPROVED** [review]

**Pull request merged**
